name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_DEPLOYMENT: "false" # do not fail test when bumping release without bundling
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', truffleruby-head ] # lowest must match ruby version in gemspec
        task: [ 'default' ]
    name: ${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake
